alias caws="nvim ~/.aws/credentials"
alias dstop="docker stop \$(docker ps -q)"
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"
alias new_mysql_docker="docker run --name mysql -e MYSQL_ROOT_PASSWORD=secret -d mysql:5.7"
alias gr1="git reset --soft HEAD~1"
alias gtag="git fetch && git describe --abbrev=0 --tags"
alias gcb="git checkout -b "
alias gc="git checkout "
alias gc-="git checkout -"
alias gmain="git checkout main && git pull origin main"
alias gnext="git checkout next && git pull origin next"
alias gdev="git checkout development && git pull origin development"
alias gstash="git stash save -u"
alias gapply="git stash apply"
alias gpick="git cherry-pick --no-commit"
alias glog="git log --oneline"
alias gm="git merge --no-edit"
alias gmm="git merge main --no-edit"
alias goinit="go mod init && go mod tidy"
alias src="source ~/.zshrc"
