vim.cmd.colorscheme("github_dark_default")
vim.cmd("hi Normal ctermbg=NONE guibg=NONE")
vim.cmd("hi NormalNC ctermbg=NONE guibg=NONE")
vim.cmd("hi Float ctermbg=NONE guibg=NONE")
vim.cmd("hi FloatBorder ctermbg=NONE guibg=NONE")
