alias gr1="git reset --soft HEAD~1"
alias gtag="git describe --abbrev=0 --tags"
alias gcb="git checkout -b "
alias gc="git checkout "
alias gmain="git checkout main && git pull"
alias gnext="git checkout next && git pull"
alias gdev="git checkout development && git pull"
alias gstash="git stash save -u"
alias gapply="git stash apply"
alias gpick="git cherry-pick --no-commit"
alias glog="git log --oneline"
alias goinit="go mod init && go mod tidy"
alias gpr="gh pr create -a @me -w"