require('kcalixto.config.options')
require('kcalixto.lazy')
require('kcalixto.config.keymaps')
require('kcalixto.completion')
require('kcalixto.lsp')
require('kcalixto.colorscheme')
require('kcalixto.functions')
require('leap').create_default_mappings()
